/* soapH.h
   Generated by gSOAP 2.8.6 from WsApi.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_begin_send(soap) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef soap_write_time
#define soap_write_time(soap, data) ( soap_begin_send(soap) || soap_put_time(soap, data, "dateTime", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#ifndef soap_read_time
#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__loginResponse
#define SOAP_TYPE__ns1__loginResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__loginResponse(struct soap*, const char*, int, const _ns1__loginResponse *, const char*);
SOAP_FMAC3 _ns1__loginResponse * SOAP_FMAC4 soap_in__ns1__loginResponse(struct soap*, const char*, _ns1__loginResponse *, const char*);

#ifndef soap_write__ns1__loginResponse
#define soap_write__ns1__loginResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:loginResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__loginResponse
#define soap_read__ns1__loginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__loginResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__loginResponse * SOAP_FMAC4 soap_get__ns1__loginResponse(struct soap*, _ns1__loginResponse *, const char*, const char*);

#define soap_new__ns1__loginResponse(soap, n) soap_instantiate__ns1__loginResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__loginResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__loginResponse * SOAP_FMAC2 soap_instantiate__ns1__loginResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__loginResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__login
#define SOAP_TYPE__ns1__login (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__login(struct soap*, const char*, int, const _ns1__login *, const char*);
SOAP_FMAC3 _ns1__login * SOAP_FMAC4 soap_in__ns1__login(struct soap*, const char*, _ns1__login *, const char*);

#ifndef soap_write__ns1__login
#define soap_write__ns1__login(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:login", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__login
#define soap_read__ns1__login(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__login(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__login * SOAP_FMAC4 soap_get__ns1__login(struct soap*, _ns1__login *, const char*, const char*);

#define soap_new__ns1__login(soap, n) soap_instantiate__ns1__login(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__login(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__login * SOAP_FMAC2 soap_instantiate__ns1__login(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getTorneioResponse
#define SOAP_TYPE__ns1__getTorneioResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getTorneioResponse(struct soap*, const char*, int, const _ns1__getTorneioResponse *, const char*);
SOAP_FMAC3 _ns1__getTorneioResponse * SOAP_FMAC4 soap_in__ns1__getTorneioResponse(struct soap*, const char*, _ns1__getTorneioResponse *, const char*);

#ifndef soap_write__ns1__getTorneioResponse
#define soap_write__ns1__getTorneioResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getTorneioResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__getTorneioResponse
#define soap_read__ns1__getTorneioResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getTorneioResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__getTorneioResponse * SOAP_FMAC4 soap_get__ns1__getTorneioResponse(struct soap*, _ns1__getTorneioResponse *, const char*, const char*);

#define soap_new__ns1__getTorneioResponse(soap, n) soap_instantiate__ns1__getTorneioResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__getTorneioResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__getTorneioResponse * SOAP_FMAC2 soap_instantiate__ns1__getTorneioResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getTorneioResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getTorneio
#define SOAP_TYPE__ns1__getTorneio (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getTorneio(struct soap*, const char*, int, const _ns1__getTorneio *, const char*);
SOAP_FMAC3 _ns1__getTorneio * SOAP_FMAC4 soap_in__ns1__getTorneio(struct soap*, const char*, _ns1__getTorneio *, const char*);

#ifndef soap_write__ns1__getTorneio
#define soap_write__ns1__getTorneio(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getTorneio", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__getTorneio
#define soap_read__ns1__getTorneio(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getTorneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__getTorneio * SOAP_FMAC4 soap_get__ns1__getTorneio(struct soap*, _ns1__getTorneio *, const char*, const char*);

#define soap_new__ns1__getTorneio(soap, n) soap_instantiate__ns1__getTorneio(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__getTorneio(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__getTorneio * SOAP_FMAC2 soap_instantiate__ns1__getTorneio(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getTorneio(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__setResultadosResponse
#define SOAP_TYPE__ns1__setResultadosResponse (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__setResultadosResponse(struct soap*, const char*, int, const _ns1__setResultadosResponse *, const char*);
SOAP_FMAC3 _ns1__setResultadosResponse * SOAP_FMAC4 soap_in__ns1__setResultadosResponse(struct soap*, const char*, _ns1__setResultadosResponse *, const char*);

#ifndef soap_write__ns1__setResultadosResponse
#define soap_write__ns1__setResultadosResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:setResultadosResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__setResultadosResponse
#define soap_read__ns1__setResultadosResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__setResultadosResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__setResultadosResponse * SOAP_FMAC4 soap_get__ns1__setResultadosResponse(struct soap*, _ns1__setResultadosResponse *, const char*, const char*);

#define soap_new__ns1__setResultadosResponse(soap, n) soap_instantiate__ns1__setResultadosResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__setResultadosResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__setResultadosResponse * SOAP_FMAC2 soap_instantiate__ns1__setResultadosResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__setResultadosResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__setResultados
#define SOAP_TYPE__ns1__setResultados (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__setResultados(struct soap*, const char*, int, const _ns1__setResultados *, const char*);
SOAP_FMAC3 _ns1__setResultados * SOAP_FMAC4 soap_in__ns1__setResultados(struct soap*, const char*, _ns1__setResultados *, const char*);

#ifndef soap_write__ns1__setResultados
#define soap_write__ns1__setResultados(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:setResultados", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__setResultados
#define soap_read__ns1__setResultados(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__setResultados(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__setResultados * SOAP_FMAC4 soap_get__ns1__setResultados(struct soap*, _ns1__setResultados *, const char*, const char*);

#define soap_new__ns1__setResultados(soap, n) soap_instantiate__ns1__setResultados(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__setResultados(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__setResultados * SOAP_FMAC2 soap_instantiate__ns1__setResultados(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__setResultados(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__Torneio
#define SOAP_TYPE_ns1__Torneio (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Torneio(struct soap*, const char*, int, const ns1__Torneio *, const char*);
SOAP_FMAC3 ns1__Torneio * SOAP_FMAC4 soap_in_ns1__Torneio(struct soap*, const char*, ns1__Torneio *, const char*);

#ifndef soap_write_ns1__Torneio
#define soap_write_ns1__Torneio(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Torneio", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns1__Torneio
#define soap_read_ns1__Torneio(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__Torneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__Torneio * SOAP_FMAC4 soap_get_ns1__Torneio(struct soap*, ns1__Torneio *, const char*, const char*);

#define soap_new_ns1__Torneio(soap, n) soap_instantiate_ns1__Torneio(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__Torneio(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__Torneio * SOAP_FMAC2 soap_instantiate_ns1__Torneio(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Torneio(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfTorneio
#define SOAP_TYPE_ns1__ArrayOfTorneio (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfTorneio(struct soap*, const char*, int, const ns1__ArrayOfTorneio *, const char*);
SOAP_FMAC3 ns1__ArrayOfTorneio * SOAP_FMAC4 soap_in_ns1__ArrayOfTorneio(struct soap*, const char*, ns1__ArrayOfTorneio *, const char*);

#ifndef soap_write_ns1__ArrayOfTorneio
#define soap_write_ns1__ArrayOfTorneio(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ArrayOfTorneio", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns1__ArrayOfTorneio
#define soap_read_ns1__ArrayOfTorneio(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ArrayOfTorneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__ArrayOfTorneio * SOAP_FMAC4 soap_get_ns1__ArrayOfTorneio(struct soap*, ns1__ArrayOfTorneio *, const char*, const char*);

#define soap_new_ns1__ArrayOfTorneio(soap, n) soap_instantiate_ns1__ArrayOfTorneio(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__ArrayOfTorneio(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__ArrayOfTorneio * SOAP_FMAC2 soap_instantiate_ns1__ArrayOfTorneio(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfTorneio(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__Classificacao
#define SOAP_TYPE_ns1__Classificacao (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Classificacao(struct soap*, const char*, int, const ns1__Classificacao *, const char*);
SOAP_FMAC3 ns1__Classificacao * SOAP_FMAC4 soap_in_ns1__Classificacao(struct soap*, const char*, ns1__Classificacao *, const char*);

#ifndef soap_write_ns1__Classificacao
#define soap_write_ns1__Classificacao(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Classificacao", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns1__Classificacao
#define soap_read_ns1__Classificacao(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__Classificacao(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__Classificacao * SOAP_FMAC4 soap_get_ns1__Classificacao(struct soap*, ns1__Classificacao *, const char*, const char*);

#define soap_new_ns1__Classificacao(soap, n) soap_instantiate_ns1__Classificacao(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__Classificacao(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__Classificacao * SOAP_FMAC2 soap_instantiate_ns1__Classificacao(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Classificacao(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfClassificacao
#define SOAP_TYPE_ns1__ArrayOfClassificacao (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfClassificacao(struct soap*, const char*, int, const ns1__ArrayOfClassificacao *, const char*);
SOAP_FMAC3 ns1__ArrayOfClassificacao * SOAP_FMAC4 soap_in_ns1__ArrayOfClassificacao(struct soap*, const char*, ns1__ArrayOfClassificacao *, const char*);

#ifndef soap_write_ns1__ArrayOfClassificacao
#define soap_write_ns1__ArrayOfClassificacao(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ArrayOfClassificacao", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns1__ArrayOfClassificacao
#define soap_read_ns1__ArrayOfClassificacao(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ArrayOfClassificacao(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__ArrayOfClassificacao * SOAP_FMAC4 soap_get_ns1__ArrayOfClassificacao(struct soap*, ns1__ArrayOfClassificacao *, const char*, const char*);

#define soap_new_ns1__ArrayOfClassificacao(soap, n) soap_instantiate_ns1__ArrayOfClassificacao(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__ArrayOfClassificacao(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__ArrayOfClassificacao * SOAP_FMAC2 soap_instantiate_ns1__ArrayOfClassificacao(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfClassificacao(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns3__login
#define SOAP_TYPE___ns3__login (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__login(struct soap*, struct __ns3__login *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__login(struct soap*, const struct __ns3__login *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__login(struct soap*, const char*, int, const struct __ns3__login *, const char*);
SOAP_FMAC3 struct __ns3__login * SOAP_FMAC4 soap_in___ns3__login(struct soap*, const char*, struct __ns3__login *, const char*);

#ifndef soap_write___ns3__login
#define soap_write___ns3__login(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__login(soap, data), 0) || soap_put___ns3__login(soap, data, "-ns3:login", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__login(struct soap*, const struct __ns3__login *, const char*, const char*);

#ifndef soap_read___ns3__login
#define soap_read___ns3__login(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__login(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__login * SOAP_FMAC4 soap_get___ns3__login(struct soap*, struct __ns3__login *, const char*, const char*);

#define soap_new___ns3__login(soap, n) soap_instantiate___ns3__login(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__login(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__login * SOAP_FMAC2 soap_instantiate___ns3__login(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__getTorneio
#define SOAP_TYPE___ns3__getTorneio (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__getTorneio(struct soap*, struct __ns3__getTorneio *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__getTorneio(struct soap*, const struct __ns3__getTorneio *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__getTorneio(struct soap*, const char*, int, const struct __ns3__getTorneio *, const char*);
SOAP_FMAC3 struct __ns3__getTorneio * SOAP_FMAC4 soap_in___ns3__getTorneio(struct soap*, const char*, struct __ns3__getTorneio *, const char*);

#ifndef soap_write___ns3__getTorneio
#define soap_write___ns3__getTorneio(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__getTorneio(soap, data), 0) || soap_put___ns3__getTorneio(soap, data, "-ns3:getTorneio", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__getTorneio(struct soap*, const struct __ns3__getTorneio *, const char*, const char*);

#ifndef soap_read___ns3__getTorneio
#define soap_read___ns3__getTorneio(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__getTorneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__getTorneio * SOAP_FMAC4 soap_get___ns3__getTorneio(struct soap*, struct __ns3__getTorneio *, const char*, const char*);

#define soap_new___ns3__getTorneio(soap, n) soap_instantiate___ns3__getTorneio(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__getTorneio(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__getTorneio * SOAP_FMAC2 soap_instantiate___ns3__getTorneio(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__getTorneio(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__setResultados
#define SOAP_TYPE___ns3__setResultados (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__setResultados(struct soap*, struct __ns3__setResultados *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__setResultados(struct soap*, const struct __ns3__setResultados *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__setResultados(struct soap*, const char*, int, const struct __ns3__setResultados *, const char*);
SOAP_FMAC3 struct __ns3__setResultados * SOAP_FMAC4 soap_in___ns3__setResultados(struct soap*, const char*, struct __ns3__setResultados *, const char*);

#ifndef soap_write___ns3__setResultados
#define soap_write___ns3__setResultados(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__setResultados(soap, data), 0) || soap_put___ns3__setResultados(soap, data, "-ns3:setResultados", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__setResultados(struct soap*, const struct __ns3__setResultados *, const char*, const char*);

#ifndef soap_read___ns3__setResultados
#define soap_read___ns3__setResultados(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__setResultados(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__setResultados * SOAP_FMAC4 soap_get___ns3__setResultados(struct soap*, struct __ns3__setResultados *, const char*, const char*);

#define soap_new___ns3__setResultados(soap, n) soap_instantiate___ns3__setResultados(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__setResultados(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__setResultados * SOAP_FMAC2 soap_instantiate___ns3__setResultados(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__setResultados(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__login
#define SOAP_TYPE___ns2__login (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__login(struct soap*, struct __ns2__login *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__login(struct soap*, const struct __ns2__login *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__login(struct soap*, const char*, int, const struct __ns2__login *, const char*);
SOAP_FMAC3 struct __ns2__login * SOAP_FMAC4 soap_in___ns2__login(struct soap*, const char*, struct __ns2__login *, const char*);

#ifndef soap_write___ns2__login
#define soap_write___ns2__login(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__login(soap, data), 0) || soap_put___ns2__login(soap, data, "-ns2:login", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__login(struct soap*, const struct __ns2__login *, const char*, const char*);

#ifndef soap_read___ns2__login
#define soap_read___ns2__login(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__login(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__login * SOAP_FMAC4 soap_get___ns2__login(struct soap*, struct __ns2__login *, const char*, const char*);

#define soap_new___ns2__login(soap, n) soap_instantiate___ns2__login(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__login(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__login * SOAP_FMAC2 soap_instantiate___ns2__login(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__getTorneio
#define SOAP_TYPE___ns2__getTorneio (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__getTorneio(struct soap*, struct __ns2__getTorneio *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__getTorneio(struct soap*, const struct __ns2__getTorneio *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__getTorneio(struct soap*, const char*, int, const struct __ns2__getTorneio *, const char*);
SOAP_FMAC3 struct __ns2__getTorneio * SOAP_FMAC4 soap_in___ns2__getTorneio(struct soap*, const char*, struct __ns2__getTorneio *, const char*);

#ifndef soap_write___ns2__getTorneio
#define soap_write___ns2__getTorneio(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__getTorneio(soap, data), 0) || soap_put___ns2__getTorneio(soap, data, "-ns2:getTorneio", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__getTorneio(struct soap*, const struct __ns2__getTorneio *, const char*, const char*);

#ifndef soap_read___ns2__getTorneio
#define soap_read___ns2__getTorneio(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__getTorneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__getTorneio * SOAP_FMAC4 soap_get___ns2__getTorneio(struct soap*, struct __ns2__getTorneio *, const char*, const char*);

#define soap_new___ns2__getTorneio(soap, n) soap_instantiate___ns2__getTorneio(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__getTorneio(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__getTorneio * SOAP_FMAC2 soap_instantiate___ns2__getTorneio(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__getTorneio(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__setResultados
#define SOAP_TYPE___ns2__setResultados (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__setResultados(struct soap*, struct __ns2__setResultados *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__setResultados(struct soap*, const struct __ns2__setResultados *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__setResultados(struct soap*, const char*, int, const struct __ns2__setResultados *, const char*);
SOAP_FMAC3 struct __ns2__setResultados * SOAP_FMAC4 soap_in___ns2__setResultados(struct soap*, const char*, struct __ns2__setResultados *, const char*);

#ifndef soap_write___ns2__setResultados
#define soap_write___ns2__setResultados(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__setResultados(soap, data), 0) || soap_put___ns2__setResultados(soap, data, "-ns2:setResultados", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__setResultados(struct soap*, const struct __ns2__setResultados *, const char*, const char*);

#ifndef soap_read___ns2__setResultados
#define soap_read___ns2__setResultados(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__setResultados(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__setResultados * SOAP_FMAC4 soap_get___ns2__setResultados(struct soap*, struct __ns2__setResultados *, const char*, const char*);

#define soap_new___ns2__setResultados(soap, n) soap_instantiate___ns2__setResultados(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__setResultados(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__setResultados * SOAP_FMAC2 soap_instantiate___ns2__setResultados(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__setResultados(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__loginResponse
#define SOAP_TYPE_PointerTo_ns1__loginResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__loginResponse(struct soap*, _ns1__loginResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__loginResponse(struct soap*, const char *, int, _ns1__loginResponse *const*, const char *);
SOAP_FMAC3 _ns1__loginResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__loginResponse(struct soap*, const char*, _ns1__loginResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__loginResponse
#define soap_write_PointerTo_ns1__loginResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__loginResponse(soap, data), 0) || soap_put_PointerTo_ns1__loginResponse(soap, data, "ns1:loginResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__loginResponse(struct soap*, _ns1__loginResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__loginResponse
#define soap_read_PointerTo_ns1__loginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__loginResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__loginResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__loginResponse(struct soap*, _ns1__loginResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__login
#define SOAP_TYPE_PointerTo_ns1__login (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__login(struct soap*, _ns1__login *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__login(struct soap*, const char *, int, _ns1__login *const*, const char *);
SOAP_FMAC3 _ns1__login ** SOAP_FMAC4 soap_in_PointerTo_ns1__login(struct soap*, const char*, _ns1__login **, const char*);

#ifndef soap_write_PointerTo_ns1__login
#define soap_write_PointerTo_ns1__login(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__login(soap, data), 0) || soap_put_PointerTo_ns1__login(soap, data, "ns1:login", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__login(struct soap*, _ns1__login *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__login
#define soap_read_PointerTo_ns1__login(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__login(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__login ** SOAP_FMAC4 soap_get_PointerTo_ns1__login(struct soap*, _ns1__login **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getTorneioResponse
#define SOAP_TYPE_PointerTo_ns1__getTorneioResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getTorneioResponse(struct soap*, _ns1__getTorneioResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getTorneioResponse(struct soap*, const char *, int, _ns1__getTorneioResponse *const*, const char *);
SOAP_FMAC3 _ns1__getTorneioResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getTorneioResponse(struct soap*, const char*, _ns1__getTorneioResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__getTorneioResponse
#define soap_write_PointerTo_ns1__getTorneioResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__getTorneioResponse(soap, data), 0) || soap_put_PointerTo_ns1__getTorneioResponse(soap, data, "ns1:getTorneioResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getTorneioResponse(struct soap*, _ns1__getTorneioResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getTorneioResponse
#define soap_read_PointerTo_ns1__getTorneioResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getTorneioResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__getTorneioResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getTorneioResponse(struct soap*, _ns1__getTorneioResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getTorneio
#define SOAP_TYPE_PointerTo_ns1__getTorneio (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getTorneio(struct soap*, _ns1__getTorneio *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getTorneio(struct soap*, const char *, int, _ns1__getTorneio *const*, const char *);
SOAP_FMAC3 _ns1__getTorneio ** SOAP_FMAC4 soap_in_PointerTo_ns1__getTorneio(struct soap*, const char*, _ns1__getTorneio **, const char*);

#ifndef soap_write_PointerTo_ns1__getTorneio
#define soap_write_PointerTo_ns1__getTorneio(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__getTorneio(soap, data), 0) || soap_put_PointerTo_ns1__getTorneio(soap, data, "ns1:getTorneio", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getTorneio(struct soap*, _ns1__getTorneio *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getTorneio
#define soap_read_PointerTo_ns1__getTorneio(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getTorneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__getTorneio ** SOAP_FMAC4 soap_get_PointerTo_ns1__getTorneio(struct soap*, _ns1__getTorneio **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__setResultadosResponse
#define SOAP_TYPE_PointerTo_ns1__setResultadosResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__setResultadosResponse(struct soap*, _ns1__setResultadosResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__setResultadosResponse(struct soap*, const char *, int, _ns1__setResultadosResponse *const*, const char *);
SOAP_FMAC3 _ns1__setResultadosResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__setResultadosResponse(struct soap*, const char*, _ns1__setResultadosResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__setResultadosResponse
#define soap_write_PointerTo_ns1__setResultadosResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__setResultadosResponse(soap, data), 0) || soap_put_PointerTo_ns1__setResultadosResponse(soap, data, "ns1:setResultadosResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__setResultadosResponse(struct soap*, _ns1__setResultadosResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__setResultadosResponse
#define soap_read_PointerTo_ns1__setResultadosResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__setResultadosResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__setResultadosResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__setResultadosResponse(struct soap*, _ns1__setResultadosResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__setResultados
#define SOAP_TYPE_PointerTo_ns1__setResultados (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__setResultados(struct soap*, _ns1__setResultados *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__setResultados(struct soap*, const char *, int, _ns1__setResultados *const*, const char *);
SOAP_FMAC3 _ns1__setResultados ** SOAP_FMAC4 soap_in_PointerTo_ns1__setResultados(struct soap*, const char*, _ns1__setResultados **, const char*);

#ifndef soap_write_PointerTo_ns1__setResultados
#define soap_write_PointerTo_ns1__setResultados(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__setResultados(soap, data), 0) || soap_put_PointerTo_ns1__setResultados(soap, data, "ns1:setResultados", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__setResultados(struct soap*, _ns1__setResultados *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__setResultados
#define soap_read_PointerTo_ns1__setResultados(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__setResultados(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__setResultados ** SOAP_FMAC4 soap_get_PointerTo_ns1__setResultados(struct soap*, _ns1__setResultados **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfTorneio
#define SOAP_TYPE_PointerTons1__ArrayOfTorneio (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfTorneio(struct soap*, ns1__ArrayOfTorneio *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfTorneio(struct soap*, const char *, int, ns1__ArrayOfTorneio *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfTorneio ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfTorneio(struct soap*, const char*, ns1__ArrayOfTorneio **, const char*);

#ifndef soap_write_PointerTons1__ArrayOfTorneio
#define soap_write_PointerTons1__ArrayOfTorneio(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ArrayOfTorneio(soap, data), 0) || soap_put_PointerTons1__ArrayOfTorneio(soap, data, "ns1:ArrayOfTorneio", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfTorneio(struct soap*, ns1__ArrayOfTorneio *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ArrayOfTorneio
#define soap_read_PointerTons1__ArrayOfTorneio(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ArrayOfTorneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__ArrayOfTorneio ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfTorneio(struct soap*, ns1__ArrayOfTorneio **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfClassificacao
#define SOAP_TYPE_PointerTons1__ArrayOfClassificacao (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfClassificacao(struct soap*, ns1__ArrayOfClassificacao *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfClassificacao(struct soap*, const char *, int, ns1__ArrayOfClassificacao *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfClassificacao ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfClassificacao(struct soap*, const char*, ns1__ArrayOfClassificacao **, const char*);

#ifndef soap_write_PointerTons1__ArrayOfClassificacao
#define soap_write_PointerTons1__ArrayOfClassificacao(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ArrayOfClassificacao(soap, data), 0) || soap_put_PointerTons1__ArrayOfClassificacao(soap, data, "ns1:ArrayOfClassificacao", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfClassificacao(struct soap*, ns1__ArrayOfClassificacao *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ArrayOfClassificacao
#define soap_read_PointerTons1__ArrayOfClassificacao(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ArrayOfClassificacao(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__ArrayOfClassificacao ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfClassificacao(struct soap*, ns1__ArrayOfClassificacao **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__Torneio
#define SOAP_TYPE_PointerToPointerTons1__Torneio (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__Torneio(struct soap*, ns1__Torneio **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__Torneio(struct soap*, const char *, int, ns1__Torneio **const*, const char *);
SOAP_FMAC3 ns1__Torneio *** SOAP_FMAC4 soap_in_PointerToPointerTons1__Torneio(struct soap*, const char*, ns1__Torneio ***, const char*);

#ifndef soap_write_PointerToPointerTons1__Torneio
#define soap_write_PointerToPointerTons1__Torneio(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToPointerTons1__Torneio(soap, data), 0) || soap_put_PointerToPointerTons1__Torneio(soap, data, "ns1:Torneio", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__Torneio(struct soap*, ns1__Torneio **const*, const char*, const char*);

#ifndef soap_read_PointerToPointerTons1__Torneio
#define soap_read_PointerToPointerTons1__Torneio(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToPointerTons1__Torneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__Torneio *** SOAP_FMAC4 soap_get_PointerToPointerTons1__Torneio(struct soap*, ns1__Torneio ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__Torneio
#define SOAP_TYPE_PointerTons1__Torneio (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Torneio(struct soap*, ns1__Torneio *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Torneio(struct soap*, const char *, int, ns1__Torneio *const*, const char *);
SOAP_FMAC3 ns1__Torneio ** SOAP_FMAC4 soap_in_PointerTons1__Torneio(struct soap*, const char*, ns1__Torneio **, const char*);

#ifndef soap_write_PointerTons1__Torneio
#define soap_write_PointerTons1__Torneio(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__Torneio(soap, data), 0) || soap_put_PointerTons1__Torneio(soap, data, "ns1:Torneio", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Torneio(struct soap*, ns1__Torneio *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__Torneio
#define soap_read_PointerTons1__Torneio(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__Torneio(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__Torneio ** SOAP_FMAC4 soap_get_PointerTons1__Torneio(struct soap*, ns1__Torneio **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__Classificacao
#define SOAP_TYPE_PointerToPointerTons1__Classificacao (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__Classificacao(struct soap*, ns1__Classificacao **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__Classificacao(struct soap*, const char *, int, ns1__Classificacao **const*, const char *);
SOAP_FMAC3 ns1__Classificacao *** SOAP_FMAC4 soap_in_PointerToPointerTons1__Classificacao(struct soap*, const char*, ns1__Classificacao ***, const char*);

#ifndef soap_write_PointerToPointerTons1__Classificacao
#define soap_write_PointerToPointerTons1__Classificacao(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToPointerTons1__Classificacao(soap, data), 0) || soap_put_PointerToPointerTons1__Classificacao(soap, data, "ns1:Classificacao", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__Classificacao(struct soap*, ns1__Classificacao **const*, const char*, const char*);

#ifndef soap_read_PointerToPointerTons1__Classificacao
#define soap_read_PointerToPointerTons1__Classificacao(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToPointerTons1__Classificacao(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__Classificacao *** SOAP_FMAC4 soap_get_PointerToPointerTons1__Classificacao(struct soap*, ns1__Classificacao ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__Classificacao
#define SOAP_TYPE_PointerTons1__Classificacao (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Classificacao(struct soap*, ns1__Classificacao *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Classificacao(struct soap*, const char *, int, ns1__Classificacao *const*, const char *);
SOAP_FMAC3 ns1__Classificacao ** SOAP_FMAC4 soap_in_PointerTons1__Classificacao(struct soap*, const char*, ns1__Classificacao **, const char*);

#ifndef soap_write_PointerTons1__Classificacao
#define soap_write_PointerTons1__Classificacao(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__Classificacao(soap, data), 0) || soap_put_PointerTons1__Classificacao(soap, data, "ns1:Classificacao", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Classificacao(struct soap*, ns1__Classificacao *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__Classificacao
#define soap_read_PointerTons1__Classificacao(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__Classificacao(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__Classificacao ** SOAP_FMAC4 soap_get_PointerTons1__Classificacao(struct soap*, ns1__Classificacao **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
