/* soapWsApiSoap12Proxy.cpp
   Generated by gSOAP 2.8.6 from WsApi.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapWsApiSoap12Proxy.h"

WsApiSoap12Proxy::WsApiSoap12Proxy()
{	WsApiSoap12Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

WsApiSoap12Proxy::WsApiSoap12Proxy(const struct soap &_soap) : soap(_soap)
{ }

WsApiSoap12Proxy::WsApiSoap12Proxy(const char *url)
{	WsApiSoap12Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

WsApiSoap12Proxy::WsApiSoap12Proxy(soap_mode iomode)
{	WsApiSoap12Proxy_init(iomode, iomode);
}

WsApiSoap12Proxy::WsApiSoap12Proxy(const char *url, soap_mode iomode)
{	WsApiSoap12Proxy_init(iomode, iomode);
	soap_endpoint = url;
}

WsApiSoap12Proxy::WsApiSoap12Proxy(soap_mode imode, soap_mode omode)
{	WsApiSoap12Proxy_init(imode, omode);
}

WsApiSoap12Proxy::~WsApiSoap12Proxy()
{ }

void WsApiSoap12Proxy::WsApiSoap12Proxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://www.w3.org/2003/05/soap-envelope", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://www.w3.org/2003/05/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://dei.isep.ipp.pt/WsApiSoap", NULL, NULL},
	{"ns1", "http://dei.isep.ipp.pt/", NULL, NULL},
	{"ns3", "http://dei.isep.ipp.pt/WsApiSoap12", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void WsApiSoap12Proxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void WsApiSoap12Proxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *WsApiSoap12Proxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *WsApiSoap12Proxy::soap_fault()
{	return this->fault;
}

const char *WsApiSoap12Proxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *WsApiSoap12Proxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int WsApiSoap12Proxy::soap_close_socket()
{	return soap_closesock(this);
}

int WsApiSoap12Proxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void WsApiSoap12Proxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void WsApiSoap12Proxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *WsApiSoap12Proxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int WsApiSoap12Proxy::setResultados(const char *endpoint, const char *soap_action, _ns1__setResultados *ns1__setResultados, _ns1__setResultadosResponse *ns1__setResultadosResponse)
{	struct soap *soap = this;
	struct __ns3__setResultados soap_tmp___ns3__setResultados;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Lapr5WebserviceDemo/WsAPI.php";
	if (!soap_action)
		soap_action = "http://dei.isep.ipp.pt/setResultados";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__setResultados.ns1__setResultados = ns1__setResultados;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__setResultados(soap, &soap_tmp___ns3__setResultados);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__setResultados(soap, &soap_tmp___ns3__setResultados, "-ns3:setResultados", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__setResultados(soap, &soap_tmp___ns3__setResultados, "-ns3:setResultados", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setResultadosResponse)
		return soap_closesock(soap);
	ns1__setResultadosResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__setResultadosResponse->soap_get(soap, "ns1:setResultadosResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsApiSoap12Proxy::getTorneio(const char *endpoint, const char *soap_action, _ns1__getTorneio *ns1__getTorneio, _ns1__getTorneioResponse *ns1__getTorneioResponse)
{	struct soap *soap = this;
	struct __ns3__getTorneio soap_tmp___ns3__getTorneio;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Lapr5WebserviceDemo/WsAPI.php";
	if (!soap_action)
		soap_action = "http://dei.isep.ipp.pt/getTorneio";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__getTorneio.ns1__getTorneio = ns1__getTorneio;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__getTorneio(soap, &soap_tmp___ns3__getTorneio);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__getTorneio(soap, &soap_tmp___ns3__getTorneio, "-ns3:getTorneio", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__getTorneio(soap, &soap_tmp___ns3__getTorneio, "-ns3:getTorneio", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getTorneioResponse)
		return soap_closesock(soap);
	ns1__getTorneioResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getTorneioResponse->soap_get(soap, "ns1:getTorneioResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsApiSoap12Proxy::login(const char *endpoint, const char *soap_action, _ns1__login *ns1__login, _ns1__loginResponse *ns1__loginResponse)
{	struct soap *soap = this;
	struct __ns3__login soap_tmp___ns3__login;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Lapr5WebserviceDemo/WsAPI.php";
	if (!soap_action)
		soap_action = "http://dei.isep.ipp.pt/login";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__login.ns1__login = ns1__login;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__login(soap, &soap_tmp___ns3__login);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__login(soap, &soap_tmp___ns3__login, "-ns3:login", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__login(soap, &soap_tmp___ns3__login, "-ns3:login", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__loginResponse)
		return soap_closesock(soap);
	ns1__loginResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__loginResponse->soap_get(soap, "ns1:loginResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
